//go:generate go run ./cmd/gen_schemes
package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	dir := "internal/theme/schemes/base24/" // adjust to your folder
	outFile := "internal/theme/base24_schemes.go"
	packageName := "theme"

	var names []string

	entries, err := os.ReadDir(dir)
	if err != nil {
		panic(err)
	}

	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".yaml") {
			name := strings.TrimSuffix(e.Name(), ".yaml")
			names = append(names, name)
		}
	}

	f, err := os.Create(outFile)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintf(f, "package %s\n\n", packageName)
	fmt.Fprintf(f, "// Code generated by gen_schemes.go; DO NOT EDIT.\n")
	fmt.Fprintf(f, "var Schemes = []string{\n")
	for _, n := range names {
		fmt.Fprintf(f, "\t%q,\n", n)
	}
	fmt.Fprintf(f, "}\n")

	fmt.Println("✅ Generated", outFile, "with", len(names), "schemes.")
}
