name: Go Release

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v0.1.0, v1.2.3

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y libx11-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Download Dependencies
        run: go mod tidy

      - name: Build Binary
        run: |
          echo "Building reposcan ${VERSION} ..."
          go build -o reposcan .

      - name: Verify Version
        run: ./reposcan version

      - name: Trigger pkg.go.dev indexing
        run: |
          REPO="${{ github.repository }}"
          REPO_LOWER=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')
          curl -X GET "https://proxy.golang.org/github.com/$REPO_LOWER/@v/${{ github.ref_name }}.info"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: docs/release-notes/${{ github.ref_name }}.md
          generate_release_notes: false


