# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.24.x']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    # CGO_ENABLED is for clipboard package, check this https://github.com/golang-design/clipboard/pull/78
    - name: Test
      run: |
        CGO_ENABLED=0 go test -v ./...

    - name: Run Tests with CGO_ENABLED=1 (${{ matrix.go }})
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        CGO_ENABLED=1 go test -v -covermode=atomic .

    - name: Run Tests with CGO_ENABLED=0 (${{ matrix.go }})
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        CGO_ENABLED=0 go test -v -covermode=atomic .

    - name: Run Tests on Windows (${{ matrix.go }})
      if: runner.os == 'Windows'
      run: |
        go test -v -covermode=atomic .
